# This field is customizable.
ds:
  port: 8888
ps: 
  port: 5432

spring:
  # add kafka configurations below spring
  datasource:
    url: jdbc:postgresql://localhost:${ps.port}/crm
    # This field is customizable.
    username: postgres
    # This field is customizable.
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Local host server port, can be changed
server:
  # This field is customizable.
  port: 8089

eureka:
  client:
    serviceUrl:
      # This field port is customizable, if it changed eureka routes must be changed as well.
      defaultZone: http://localhost:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
