spring:
  # add kafka configurations below spring
  datasource:
    # This field is customizable.
    url: jdbc:postgresql://localhost:5432/crm
    # This field is customizable.
    username: postgres
    # This field is customizable.
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  # This field is customizable.
  port: 8083

eureka:
  client:
    serviceUrl:
      # This field port is customizable, if it changed eureka routes must be changed as well.
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
