spring:
  application:
    name: discoveryserver
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      # This field port section is customizable.
      defaultZone: http://discoveryserver:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  
