spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: eureka
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**
          
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
