spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      mvc:
        routes:
          - id: eureka
            uri: http://discoveryserver:${server.port}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-static
            uri: http://discoveryserver:${server.port}
            predicates:
              - Path=/eureka/**
server:
  port: 8080
          
eureka:
  client:
    serviceUrl:
      # This field port is customizable, if it changed eureka routes must be changed as well.
      defaultZone: http://discoveryserver:${server.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
